parameters:
    app.mailer.sender_email: 'badissbenzarti@gmail.com'
    app.mailer.recipient_email: 'badissbenzarti@gmail.com'  # Add recipient email

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\MailerService:
        arguments:
            $senderEmail: '%app.mailer.sender_email%'
            $recipientEmail: '%app.mailer.recipient_email%'